-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color0 = '#DE935F'
local Color1 = '#AF9054'
local Color2 = '#85678F'
local Color6 = '#8C9440'
local Color7 = '#FCEED1'
local Color10 = '#f4f0d9'
local Color11 = '#f7e4d9'
local Color12 = '#e7dfcd'
local Color13 = '#6B552A'
local Color5 = '#563D0E'
local Color3 = '#CC6666'
local Color4 = '#5F819D'
local Color9 = '#FEF8EB'
local Color8 = '#564422'

highlight('Number', nil, Color0, nil)
highlight('Comment', nil, Color1, nil)
highlight('Keyword', nil, Color2, nil)
highlight('Type', nil, Color2, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color4, nil)
highlight('Identifier', nil, Color5, nil)
highlight('Constant', nil, Color3, nil)
highlight('String', nil, Color6, nil)
highlight('StatusLine', Color8, Color7, nil)
highlight('WildMenu', Color9, Color5, nil)
highlight('Pmenu', Color9, Color5, nil)
highlight('PmenuSel', Color5, Color9, nil)
highlight('PmenuThumb', Color9, Color5, nil)
highlight('DiffAdd', Color10, nil, nil)
highlight('DiffDelete', Color11, nil, nil)
highlight('Normal', Color9, Color5, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color13, nil)
highlight('TabLine', Color7, Color13, nil)
highlight('TabLineSel', Color5, Color9, nil)
highlight('TabLineFill', Color7, Color13, nil)
highlight('TSPunctDelimiter', nil, Color5, nil)

link('CursorLineNr', 'Identifier')
link('TSComment', 'Comment')
link('TSField', 'Constant')
link('Folded', 'Comment')
link('TSKeyword', 'Keyword')
link('TSFloat', 'Number')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('NonText', 'Comment')
link('TSPunctBracket', 'MyTag')
link('TSString', 'String')
link('TSFuncMacro', 'Macro')
link('Operator', 'Keyword')
link('TSParameter', 'Constant')
link('Whitespace', 'Comment')
link('TelescopeNormal', 'Normal')
link('TSProperty', 'TSField')
link('TSTag', 'MyTag')
link('TSConstant', 'Constant')
link('TSTagDelimiter', 'Type')
link('TSNumber', 'Number')
link('TSConditional', 'Conditional')
link('TSLabel', 'Type')
link('Macro', 'Function')
link('TSType', 'Type')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Conditional', 'Operator')
link('TSNamespace', 'TSType')
link('TSFunction', 'Function')
link('TSRepeat', 'Repeat')
link('TSParameterReference', 'TSParameter')
link('Repeat', 'Conditional')
link('TSOperator', 'Operator')
