-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color3 = '#B39696'
local Color9 = '#485059'
local Color2 = '#FF5370'
local Color5 = '#D9C891'
local Color0 = '#586270'
local Color1 = '#FFFFFF'
local Color7 = '#1e1e1e'
local Color8 = '#d4d4d4'
local Color6 = '#5A7CA4'
local Color4 = '#8C9FB8'

highlight('Comment', nil, Color0, nil)
highlight('Identifier', nil, Color1, nil)
highlight('Error', nil, Color2, nil)
highlight('Conditional', nil, Color3, nil)
highlight('Repeat', nil, Color3, nil)
highlight('Operator', nil, Color1, nil)
highlight('Function', nil, Color4, nil)
highlight('Number', nil, Color5, nil)
highlight('TSCharacter', nil, Color5, nil)
highlight('StatusLine', nil, Color6, nil)
highlight('WildMenu', Color7, Color8, nil)
highlight('Pmenu', Color7, Color8, nil)
highlight('PmenuSel', Color8, nil, nil)
highlight('PmenuThumb', Color2, nil, nil)
highlight('Normal', Color7, Color8, nil)
highlight('Visual', Color9, nil, nil)
highlight('CursorLine', Color9, nil, nil)
highlight('ColorColumn', Color9, nil, nil)
highlight('SignColumn', Color7, nil, nil)
highlight('LineNr', nil, Color0, nil)
highlight('TSPunctDelimiter', nil, Color8, nil)

highlight('Special', nil, Color3, nil)
highlight('Delimiter', nil, Color2, nil)
highlight('@variable', nil, Color8, nil)

-- finding some last little stragglers
highlight('Directory', nil, Color4, nil)

highlight('DiagnosticHint', nil, Color4, nil)
highlight('DiagnosticWarn', nil, Color3, nil)
highlight('DiagnosticError', nil, Color2, nil)

link('TSRepeat', 'Repeat')
link('TSFuncMacro', 'Macro')
link('TSPunctBracket', 'MyTag')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSTagDelimiter', 'Type')
link('NonText', 'Comment')
link('TelescopeNormal', 'Normal')
link('TSFloat', 'Number')
link('TSOperator', 'Operator')
link('TSNamespace', 'TSType')
link('TSConditional', 'Conditional')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Macro', 'Function')
link('TSTag', 'MyTag')
link('TSField', 'Constant')
link('TSString', 'String')
link('TSConstant', 'Constant')
link('Folded', 'Comment')
link('Repeat', 'Conditional')
link('CursorLineNr', 'Identifier')
link('Whitespace', 'Comment')
link('Operator', 'Keyword')
link('TSParameterReference', 'TSParameter')
link('TSFunction', 'Function')
link('TSProperty', 'TSField')
link('TSNumber', 'Number')
link('TSType', 'Type')
link('Conditional', 'Operator')
link('TSParameter', 'Constant')
link('TSLabel', 'Type')
link('TSComment', 'Comment')
link('TSKeyword', 'Keyword')

vim.fn.sign_define('DapStopped', { linehl = "PmenuThumb" })
