-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color1 = '#bbbbbb'
local Color0 = '#6b6b6b'
local Color3 = '#111111'
local Color2 = '#333333'
local Color4 = '#cccccc'
local Color5 = '#4b4b4f'

highlight('Comment', nil, Color5, nil)
highlight('Keyword', nil, Color0, nil)
highlight('Statement', nil, Color0, nil)
highlight('Constant', nil, Color1, nil)
highlight('Type', nil, Color0, nil)
highlight('Error', nil, Color0, nil)
highlight('StatusLine', Color1, Color2, nil)
highlight('WildMenu', Color3, Color1, nil)
highlight('Pmenu', Color3, Color1, nil)
highlight('PmenuSel', Color1, Color2, nil)
highlight('PmenuThumb', Color0, Color1, nil)
highlight('DiffAdd', Color2, nil, nil)
highlight('DiffDelete', Color2, nil, nil)
highlight('Normal', Color3, Color1, nil)
highlight('Visual', Color2, nil, nil)
highlight('CursorLine', Color2, nil, nil)
highlight('ColorColumn', Color2, nil, nil)
highlight('SignColumn', Color3, nil, nil)
highlight('LineNr', nil, Color2, nil)
highlight('TabLine', Color3, Color0, nil)
highlight('TabLineSel', Color1, Color2, nil)
highlight('TabLineFill', Color3, Color0, nil)
highlight('TSPunctDelimiter', nil, Color1, nil)

highlight('Identifier', nil, Color0, nil)
highlight('Conditional', nil, Color1, nil)
highlight('Repeat', nil, Color2, nil)
highlight('Operator', nil, Color0, nil)
highlight('Function', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('String', nil, Color0, nil)
highlight('Special', nil, Color2, nil)
highlight('TSCharacter', nil, Color0, nil)
highlight('Delimiter', nil, Color4, nil)
highlight('@variable', nil, Color4, nil)
highlight('PreProc', nil, Color4, nil)

-- finding some last little stragglers
highlight('Directory', nil, Color4, nil)
highlight('DiagnosticHint', nil, Color2, nil)
highlight('DiagnosticWarn', nil, Color0, nil)
highlight('DiagnosticError', nil, Color4, nil)

link('NonText', 'Comment')
link('TSConditional', 'Conditional')
link('TSConstant', 'Constant')
link('Macro', 'Function')
link('TSType', 'Type')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Conditional', 'Operator')
link('TSProperty', 'TSField')
link('TSKeyword', 'Keyword')
link('TSComment', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TelescopeNormal', 'Normal')
link('TSLabel', 'Type')
link('TSString', 'String')
link('TSNamespace', 'TSType')
link('TSPunctBracket', 'MyTag')
link('TSTag', 'MyTag')
link('Folded', 'Comment')
link('TSOperator', 'Operator')
link('TSRepeat', 'Repeat')
link('TSFunction', 'Function')
link('TSTagDelimiter', 'Type')
link('TSParameter', 'Constant')
link('Operator', 'Keyword')
link('TSField', 'Constant')
link('TSFuncMacro', 'Macro')
link('TSNumber', 'Number')
link('CursorLineNr', 'Identifier')
link('Repeat', 'Conditional')
link('TSParameterReference', 'TSParameter')
link('TSFloat', 'Number')
link('Whitespace', 'Comment')

vim.fn.sign_define('DapStopped', { linehl = "PmenuThumb" })
