-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color7 = '#272932'
local Color14 = '#b9b50f'
local Color2 = '#37EBF3'
local Color4 = '#0E79B2'
local Color8 = '#2c656e'
local Color10 = '#3f393e'
local Color1 = '#6272A4'
local Color11 = '#2a4d56'
local Color12 = '#9370DB'
local Color0 = '#FF5555'
local Color9 = '#2f2e3f'
local Color5 = '#E455AE'
local Color6 = '#FDF500'
local Color13 = '#29414a'
local Color3 = '#2CF6B3'

highlight('Error', nil, Color0, nil)
highlight('Comment', nil, Color1, nil)
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color4, nil)
highlight('Type', nil, Color5, 'italic')
highlight('String', nil, Color6, nil)
highlight('Identifier', nil, Color2, nil)
highlight('StatusLine', Color7, Color6, nil)
highlight('WildMenu', Color7, Color6, nil)
highlight('Pmenu', Color7, Color6, nil)
highlight('PmenuSel', Color6, Color8, nil)
highlight('PmenuThumb', Color0, nil, nil)
highlight('DiffAdd', Color9, nil, nil)
highlight('DiffDelete', Color10, nil, nil)
highlight('Normal', Color7, Color6, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color7, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color13, Color14, nil)
highlight('TabLineSel', Color6, Color8, nil)
highlight('TabLineFill', Color13, Color14, nil)
highlight('TSPunctDelimiter', nil, Color6, nil)

highlight('Conditional', nil, Color12, nil)
highlight('Repeat', nil, Color5, nil)
highlight('Operator', nil, Color9, nil)
highlight('Number', nil, Color14, nil)
highlight('Special', nil, Color5, nil)
highlight('TSCharacter', nil, Color6, nil)
highlight('Delimiter', nil, Color11, nil)
highlight('@variable', nil, Color8, nil)

-- finding some last little stragglers
highlight('Directory', nil, Color4, nil)
highlight('DiagnosticHint', nil, Color5, nil)
highlight('DiagnosticWarn', nil, Color5, nil)

link('Macro', 'Function')
link('TSFuncMacro', 'Macro')
link('TSLabel', 'Type')
link('TSString', 'String')
link('TSNumber', 'Number')
link('TSConstant', 'Constant')
link('Operator', 'Keyword')
link('TSParameter', 'Constant')
link('Conditional', 'Operator')
link('TSTag', 'MyTag')
link('TSComment', 'Comment')
link('TSTagDelimiter', 'Type')
link('TSField', 'Constant')
link('Whitespace', 'Comment')
link('TSKeyword', 'Keyword')
link('TSProperty', 'TSField')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSRepeat', 'Repeat')
link('Folded', 'Comment')
link('TSFunction', 'Function')
link('TSConditional', 'Conditional')
link('TelescopeNormal', 'Normal')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('NonText', 'Comment')
link('TSPunctBracket', 'MyTag')
link('Repeat', 'Conditional')
link('TSOperator', 'Operator')
link('TSType', 'Type')
link('TSNamespace', 'TSType')
link('CursorLineNr', 'Identifier')
link('TSParameterReference', 'TSParameter')
link('TSFloat', 'Number')

vim.fn.sign_define('DapStopped', { linehl = "PmenuThumb" })
