-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color5 = '#d1b7f1'
local Color8 = '#1E1E1E'
local Color0 = '#af678d'
local Color1 = '#cec4a8'
local Color10 = '#444242'
local Color6 = '#d4d4d4'
local Color7 = '#F15FB4'
local Color4 = '#e99a9a'
local Color2 = '#e83c92'
local Color3 = '#F695C6'
local Color9 = '#D4D4D4'

highlight('Comment', nil, Color0, nil)
highlight('Number', nil, Color1, nil)
highlight('Error', nil, Color2, nil)
highlight('Type', nil, Color3, nil)
highlight('String', nil, Color4, nil)
highlight('Keyword', nil, Color5, nil)
highlight('Conditional', nil, Color5, nil)
highlight('Repeat', nil, Color5, nil)
highlight('Operator', nil, Color6, nil)
highlight('StatusLine', nil, Color7, nil)
highlight('WildMenu', Color8, Color9, nil)
highlight('Pmenu', Color8, Color9, nil)
highlight('PmenuSel', Color9, nil, nil)
highlight('PmenuThumb', Color0, nil, nil)
highlight('Normal', Color8, Color0, nil)
highlight('Visual', Color10, nil, nil)
highlight('CursorLine', Color10, nil, nil)
highlight('ColorColumn', Color10, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

highlight('Identifier', nil, Color0, nil)
highlight('Function', nil, Color1, nil)
highlight('Special', nil, Color2, nil)
highlight('TSCharacter', nil, Color0, nil)
highlight('Delimiter', nil, Color4, nil)
highlight('@variable', nil, Color4, nil)

-- finding some last little stragglers
highlight('Directory', nil, Color2, nil)
highlight('DiagnosticHint', nil, Color1, nil)
highlight('DiagnosticWarn', nil, Color3, nil)
highlight('DiagnosticError', nil, Color2, nil)

link('TSType', 'Type')
link('Folded', 'Comment')
link('TSNumber', 'Number')
link('TSParameterReference', 'TSParameter')
link('TSFunction', 'Function')
link('TSString', 'String')
link('TSComment', 'Comment')
link('TSTagDelimiter', 'Type')
link('Macro', 'Function')
link('TSNamespace', 'TSType')
link('TSOperator', 'Operator')
link('Conditional', 'Operator')
link('TSField', 'Constant')
link('NonText', 'Comment')
link('TSPunctBracket', 'MyTag')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Repeat', 'Conditional')
link('TSConstant', 'Constant')
link('Whitespace', 'Comment')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSRepeat', 'Repeat')
link('TelescopeNormal', 'Normal')
link('TSFloat', 'Number')
link('TSParameter', 'Constant')
link('TSKeyword', 'Keyword')
link('TSProperty', 'TSField')
link('TSTag', 'MyTag')
link('Operator', 'Keyword')
link('TSLabel', 'Type')
link('TSFuncMacro', 'Macro')
link('TSConditional', 'Conditional')
link('CursorLineNr', 'Identifier')

vim.fn.sign_define('DapStopped', { linehl = "PmenuThumb" })
