-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color1 = '#c28e60'
local Color7 = '#f4e286'
local Color9 = '#c4cadc'
local Color13 = '#422515'
local Color0 = '#b2a8b4'
local Color14 = '#6d5139'
local Color8 = '#ecd2b4'
local Color15 = '#3c414c'
local Color2 = '#a1a7a9'
local Color11 = '#d8dce8'
local Color12 = '#473b20'
local Color10 = '#0f141c'
local Color3 = '#ba4d06'
local Color4 = '#00b4d6'
local Color16 = '#737882'
local Color6 = '#d2d8d8'
local Color5 = '#4a4e54'

highlight('Identifier', nil, Color0, nil)
highlight('Keyword', nil, Color1, nil)
highlight('String', nil, Color2, nil)
highlight('Type', nil, Color1, 'italic')
highlight('Error', nil, Color3, nil)
highlight('Conditional', nil, Color4, 'italic')
highlight('Repeat', nil, Color4, 'italic')
highlight('Comment', nil, Color5, 'italic')
highlight('Type', nil, Color6, nil)
highlight('Function', nil, Color7, nil)
highlight('Number', nil, Color8, nil)
highlight('TSCharacter', nil, Color8, nil)
highlight('StatusLine', Color9, Color10, nil)
highlight('WildMenu', Color10, Color11, nil)
highlight('Pmenu', Color10, Color11, nil)
highlight('PmenuSel', Color11, Color10, nil)
highlight('PmenuThumb', Color4, nil, nil)
highlight('DiffAdd', Color12, nil, nil)
highlight('DiffDelete', Color13, nil, nil)
highlight('Normal', Color10, Color11, nil)
highlight('Visual', Color14, nil, nil)
highlight('CursorLine', Color14, nil, nil)
highlight('ColorColumn', Color14, nil, nil)
highlight('SignColumn', Color10, nil, nil)
highlight('LineNr', nil, Color15, nil)
highlight('TabLine', Color10, Color16, nil)
highlight('TabLineSel', Color11, Color10, nil)
highlight('TabLineFill', Color10, Color16, nil)
highlight('TSPunctDelimiter', nil, Color11, nil)

-- finding some last little stragglers
highlight('Directory', nil, Color1, nil)

highlight('DiagnosticHint', nil, Color4, nil)
highlight('DiagnosticWarn', nil, Color2, nil)
highlight('DiagnosticError', nil, Color3, nil)

link('TSNumber', 'Number')
link('Whitespace', 'Comment')
link('TSLabel', 'Type')
link('TSKeyword', 'Keyword')
link('TelescopeNormal', 'Normal')
link('TSConstant', 'Constant')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSFuncMacro', 'Macro')
link('Macro', 'Function')
link('CursorLineNr', 'Identifier')
link('TSFloat', 'Number')
link('TSTagDelimiter', 'Type')
link('TSField', 'Constant')
link('NonText', 'Comment')
link('Operator', 'Keyword')
link('TSType', 'Type')
link('TSComment', 'Comment')
link('TSString', 'String')
link('TSPunctBracket', 'MyTag')
link('TSFunction', 'Function')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSNamespace', 'TSType')
link('Repeat', 'Conditional')
link('TSParameterReference', 'TSParameter')
link('TSConditional', 'Conditional')
link('TSRepeat', 'Repeat')
link('TSParameter', 'Constant')
link('TSTag', 'MyTag')
link('Conditional', 'Operator')
link('TSProperty', 'TSField')
link('TSOperator', 'Operator')
link('Folded', 'Comment')

vim.fn.sign_define('DapStopped', { linehl = "PmenuThumb" })
