-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color9 = '#a0a0a4'
local Color0 = '#C0C0C0'
local Color2 = '#FFFF00'
local Color6 = '#000000'
local Color3 = '#7A3E9D'
local Color4 = '#FF00D6'
local Color10 = '#7C7C7C'
local Color1 = '#FFFFFF'
local Color5 = '#00FFFF'
local Color8 = '#000080'
local Color7 = '#f0f0f0'

highlight('Comment', nil, Color0, 'italic')
highlight('Operator', nil, Color1, nil)
highlight('Keyword', nil, Color1, nil)
highlight('Type', nil, Color1, nil)
highlight('Identifier', nil, Color1, nil)
highlight('Function', nil, Color2, nil)
highlight('Type', nil, Color3, 'bold')
highlight('Constant', nil, Color4, nil)
highlight('Number', nil, Color4, nil)
highlight('TSCharacter', nil, Color4, nil)
highlight('String', nil, Color5, nil)
highlight('StatusLine', Color6, Color7, nil)
highlight('WildMenu', Color8, Color2, nil)
highlight('Pmenu', Color8, Color2, nil)
highlight('PmenuSel', Color2, Color9, nil)
highlight('PmenuThumb', Color3, nil, nil)
highlight('Normal', Color8, Color2, nil)
highlight('Visual', Color10, nil, nil)
highlight('CursorLine', Color10, nil, nil)
highlight('ColorColumn', Color10, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color0, nil)
highlight('TabLine', Color7, Color6, nil)
highlight('TabLineSel', Color6, Color9, nil)
highlight('TabLineFill', Color7, Color6, nil)
highlight('TSPunctDelimiter', nil, Color2, nil)

highlight('Conditional', nil, Color1, nil)
highlight('Repeat', nil, Color2, nil)
highlight('Special', nil, Color2, nil)
highlight('Delimiter', nil, Color1, nil)
highlight('@variable', nil, Color9, nil)

link('TSConstant', 'Constant')
link('CursorLineNr', 'Identifier')
link('TSNumber', 'Number')
link('TSTagDelimiter', 'Type')
link('Macro', 'Function')
link('TSTag', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSParameter', 'Constant')
link('TSOperator', 'Operator')
link('Conditional', 'Operator')
link('TSFloat', 'Number')
link('TSComment', 'Comment')
link('TSRepeat', 'Repeat')
link('TSProperty', 'TSField')
link('TSFuncMacro', 'Macro')
link('TSNamespace', 'TSType')
link('TSLabel', 'Type')
link('Operator', 'Keyword')
link('Repeat', 'Conditional')
link('Whitespace', 'Comment')
link('TSFunction', 'Function')
link('TSString', 'String')
link('TelescopeNormal', 'Normal')
link('Folded', 'Comment')
link('TSKeyword', 'Keyword')
link('TSField', 'Constant')
link('TSConditional', 'Conditional')
link('TSType', 'Type')
link('NonText', 'Comment')
link('TSParameterReference', 'TSParameter')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSPunctBracket', 'MyTag')

vim.fn.sign_define('DapStopped', { linehl = "PmenuThumb" })
