-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color10 = '#303e53'
local Color8 = '#0a1018'
local Color4 = '#708394'
local Color11 = '#151b25'
local Color2 = '#FF5370'
local Color0 = '#546E7A'
local Color5 = '#28735E'
local Color3 = '#25a2a6'
local Color9 = '#1a2028'
local Color1 = '#EEFFFF'
local Color6 = '#242b38'
local Color7 = '#7f8796'

highlight('Comment', nil, Color0, 'italic')
highlight('Identifier', nil, Color1, nil)
highlight('Error', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Function', nil, Color5, nil)
highlight('Number', nil, Color4, nil)
highlight('TSCharacter', nil, Color4, nil)
highlight('String', nil, Color4, nil)
highlight('StatusLine', Color7, Color6, nil)
highlight('WildMenu', Color8, Color3, nil)
highlight('Pmenu', Color8, Color3, nil)
highlight('PmenuSel', Color3, Color9, nil)
highlight('PmenuThumb', Color2, Color1, nil)
highlight('Normal', Color8, Color3, nil)
highlight('Visual', Color10, nil, nil)
highlight('CursorLine', Color10, nil, nil)
highlight('ColorColumn', Color10, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('TabLine', Color11, nil, nil)
highlight('TabLineSel', nil, Color9, nil)
highlight('TabLineFill', Color11, nil, nil)
highlight('TSPunctDelimiter', nil, Color3, nil)

highlight('Operator', nil, Color0, nil)
highlight('Special', nil, Color2, nil)
highlight('Delimiter', nil, Color7, nil)
highlight('@variable', nil, Color1, nil)

highlight('DiagnosticHint', nil, Color1, nil)
highlight('DiagnosticWarn', nil, Color3, nil)
highlight('DiagnosticError', nil, Color2, nil)

link('Folded', 'Comment')
link('TSFloat', 'Number')
link('TSString', 'String')
link('TSParameterReference', 'TSParameter')
link('Whitespace', 'Comment')
link('TSConditional', 'Conditional')
link('TSTagDelimiter', 'Type')
link('TSRepeat', 'Repeat')
link('TelescopeNormal', 'Normal')
link('Repeat', 'Conditional')
link('TSType', 'Type')
link('NonText', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSFuncMacro', 'Macro')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Conditional', 'Operator')
link('TSComment', 'Comment')
link('TSLabel', 'Type')
link('Macro', 'Function')
link('TSPunctBracket', 'MyTag')
link('TSNamespace', 'TSType')
link('TSConstant', 'Constant')
link('TSOperator', 'Operator')
link('TSParameter', 'Constant')
link('Operator', 'Keyword')
link('TSNumber', 'Number')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSProperty', 'TSField')
link('TSTag', 'MyTag')
link('TSField', 'Constant')
link('TSKeyword', 'Keyword')
link('TSFunction', 'Function')

vim.fn.sign_define('DapStopped', { linehl = "PmenuThumb" })
