-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color5 = '#f7442d'
local Color8 = '#d4d4d4'
local Color0 = '#ebc17a'
local Color10 = '#41463d'
local Color6 = '#4c5c3f'
local Color7 = '#1f1f1f'
local Color4 = '#4e5350'
local Color9 = '#33382e'
local Color11 = '#1c1d1c'
local Color1 = '#83a06c'
local Color2 = '#e1f3e7'
local Color3 = '#adc586'

highlight('Number', nil, Color0, nil)
highlight('TSCharacter', nil, Color0, nil)
highlight('Keyword', nil, Color1, nil)
highlight('Identifier', nil, Color2, nil)
highlight('String', nil, Color3, nil)
highlight('Conditional', nil, Color3, nil)
highlight('Repeat', nil, Color3, nil)
highlight('Comment', nil, Color4, 'italic')
highlight('Function', nil, Color0, 'italic')
highlight('Error', nil, Color5, 'italic')
highlight('StatusLine', nil, Color6, nil)
highlight('WildMenu', Color7, Color8, nil)
highlight('Pmenu', Color7, Color8, nil)
highlight('PmenuSel', Color8, Color7, nil)
highlight('PmenuThumb', Color0, Color4, nil)
highlight('Normal', Color7, Color8, nil)
highlight('Visual', Color9, nil, nil)
highlight('CursorLine', Color9, nil, nil)
highlight('ColorColumn', Color9, nil, nil)
highlight('SignColumn', Color7, nil, nil)
highlight('LineNr', nil, Color10, nil)
highlight('TabLine', Color11, nil, nil)
highlight('TabLineSel', nil, Color7, nil)
highlight('TabLineFill', Color11, nil, nil)
highlight('TSPunctDelimiter', nil, Color8, nil)

highlight('Special', nil, Color2, nil)
highlight('Delimiter', nil, Color6, nil)
highlight('@variable', nil, Color4, nil)

-- finding some last little stragglers
highlight('Directory', nil, Color4, nil)
highlight('DiagnosticHint', nil, Color6, nil)
highlight('DiagnosticWarn', nil, Color0, nil)
highlight('DiagnosticError', nil, Color5, nil)

link('TSFuncMacro', 'Macro')
link('TSOperator', 'Operator')
link('TSNamespace', 'TSType')
link('TSKeyword', 'Keyword')
link('TSTagDelimiter', 'Type')
link('TSFloat', 'Number')
link('TSConstant', 'Constant')
link('Repeat', 'Conditional')
link('TSLabel', 'Type')
link('Folded', 'Comment')
link('TSField', 'Constant')
link('TSComment', 'Comment')
link('TSParameter', 'Constant')
link('NonText', 'Comment')
link('TSConditional', 'Conditional')
link('CursorLineNr', 'Identifier')
link('Operator', 'Keyword')
link('TSString', 'String')
link('TSFunction', 'Function')
link('TSType', 'Type')
link('TelescopeNormal', 'Normal')
link('TSRepeat', 'Repeat')
link('TSNumber', 'Number')
link('Conditional', 'Operator')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSTag', 'MyTag')
link('TSPunctBracket', 'MyTag')
link('Macro', 'Function')
link('TSProperty', 'TSField')
link('TSParameterReference', 'TSParameter')
link('Whitespace', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')

vim.fn.sign_define('DapStopped', { linehl = "PmenuThumb" })
