-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color15 = '#bdae93'
local Color3 = '#9d0006'
local Color16 = '#7c6f64'
local Color5 = '#427b58'
local Color6 = '#b57614'
local Color14 = '#d4debb'
local Color9 = '#f9f5d7'
local Color8 = '#076678'
local Color12 = '#e0dcb1'
local Color4 = '#79740e'
local Color0 = '#928374'
local Color13 = '#e7c6af'
local Color2 = '#cc241d'
local Color10 = '#3c3836'
local Color7 = '#504945'
local Color11 = '#f2e5bc'
local Color1 = '#8f3f71'

highlight('Comment', nil, Color0, 'italic')
highlight('Constant', nil, Color1, nil)
highlight('Error', nil, Color2, nil)
highlight('Type', nil, Color3, nil)
highlight('String', nil, Color4, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Conditional', nil, Color3, nil)
highlight('Repeat', nil, Color3, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('Function', nil, Color6, nil)
highlight('Type', nil, Color6, nil)
highlight('parens', nil, Color7, nil)
highlight('Identifier', nil, Color8, nil)
highlight('StatusLine', Color10, Color9, nil)
highlight('WildMenu', Color9, Color10, nil)
highlight('Pmenu', Color9, Color10, nil)
highlight('PmenuSel', Color10, Color11, nil)
highlight('PmenuThumb', Color9, Color10, nil)
highlight('DiffAdd', Color12, nil, nil)
highlight('DiffDelete', Color13, nil, nil)
highlight('Normal', Color9, Color10, nil)
highlight('Visual', Color14, nil, nil)
highlight('CursorLine', Color14, nil, nil)
highlight('ColorColumn', Color14, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color15, nil)
highlight('TabLine', Color9, Color16, nil)
highlight('TabLineSel', Color10, Color11, nil)
highlight('TabLineFill', Color9, Color16, nil)
highlight('TSPunctDelimiter', nil, Color10, nil)

link('TSComment', 'Comment')
link('Conditional', 'Operator')
link('TSConstant', 'Constant')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSProperty', 'TSField')
link('TSFloat', 'Number')
link('TSLabel', 'Type')
link('Whitespace', 'Comment')
link('TSKeyword', 'Keyword')
link('TSField', 'Constant')
link('TSNamespace', 'TSType')
link('TelescopeNormal', 'Normal')
link('TSRepeat', 'Repeat')
link('Folded', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSPunctBracket', 'MyTag')
link('TSFunction', 'Function')
link('TSNumber', 'Number')
link('TSTag', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSOperator', 'Operator')
link('TSConditional', 'Conditional')
link('TSFuncMacro', 'Macro')
link('TSString', 'String')
link('TSParameterReference', 'TSParameter')
link('Repeat', 'Conditional')
link('Operator', 'Keyword')
link('NonText', 'Comment')
link('TSTagDelimiter', 'Type')
link('Macro', 'Function')
link('TSParameter', 'Constant')
link('TSType', 'Type')
