-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color3 = '#9db166'
local Color8 = '#a7d129'
local Color9 = '#0a0f0b'
local Color7 = '#242f25'
local Color4 = '#c2df6b'
local Color10 = '#eeffff'
local Color1 = '#EEFFFF'
local Color5 = '#daf1bb'
local Color2 = '#FF5370'
local Color6 = '#C3E88D'
local Color0 = '#546E7A'

highlight('Comment', nil, Color0, 'italic')
highlight('Identifier', nil, Color1, nil)
highlight('Error', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Conditional', nil, Color3, nil)
highlight('Repeat', nil, Color3, nil)
highlight('Function', nil, Color4, 'bold')
highlight('Number', nil, Color5, nil)
highlight('TSCharacter', nil, Color5, nil)
highlight('String', nil, Color6, nil)
highlight('StatusLine', Color7, Color8, nil)
highlight('WildMenu', Color9, Color10, nil)
highlight('Pmenu', Color9, Color10, nil)
highlight('PmenuSel', Color10, Color9, nil)
highlight('PmenuThumb', Color2, nil, nil)
highlight('Normal', Color9, Color10, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('TabLine', Color9, nil, nil)
highlight('TabLineSel', nil, Color9, nil)
highlight('TabLineFill', Color9, nil, nil)
highlight('TSPunctDelimiter', nil, Color10, nil)

highlight('Special', nil, Color8, nil)

-- finding some last little stragglers
highlight('Directory', nil, Color4, nil)
highlight('DiagnosticHint', nil, Color7, nil)
highlight('DiagnosticWarn', nil, Color7, nil)

link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSConditional', 'Conditional')
link('TSFloat', 'Number')
link('TSType', 'Type')
link('Conditional', 'Operator')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TelescopeNormal', 'Normal')
link('TSKeyword', 'Keyword')
link('CursorLineNr', 'Identifier')
link('TSPunctBracket', 'MyTag')
link('TSTagDelimiter', 'Type')
link('TSFunction', 'Function')
link('TSNamespace', 'TSType')
link('Repeat', 'Conditional')
link('TSTag', 'MyTag')
link('TSConstant', 'Constant')
link('Macro', 'Function')
link('NonText', 'Comment')
link('TSParameterReference', 'TSParameter')
link('TSRepeat', 'Repeat')
link('TSFuncMacro', 'Macro')
link('Folded', 'Comment')
link('TSOperator', 'Operator')
link('TSParameter', 'Constant')
link('Operator', 'Keyword')
link('TSNumber', 'Number')
link('TSLabel', 'Type')
link('TSField', 'Constant')
link('TSString', 'String')
link('Whitespace', 'Comment')
link('TSComment', 'Comment')
link('TSProperty', 'TSField')

vim.fn.sign_define('DapStopped', { linehl = "PmenuThumb" })
