-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color4 = '#00b4d6'
local Color12 = '#89817c'
local Color13 = '#4f463e'
local Color8 = '#f6ece0'
local Color6 = '#ecd2b4'
local Color10 = '#32230c'
local Color1 = '#d2d8d8'
local Color5 = '#5d8a74'
local Color3 = '#c28e60'
local Color9 = '#fcfaf6'
local Color14 = '#bfb5aa'
local Color11 = '#301807'
local Color2 = '#c86206'
local Color0 = '#6e6864'
local Color7 = '#180f08'

highlight('Comment', nil, Color0, 'italic')
highlight('Identifier', nil, Color1, nil)
highlight('Error', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Function', nil, Color5, nil)
highlight('Number', nil, Color6, nil)
highlight('TSCharacter', nil, Color6, nil)
highlight('String', nil, Color6, nil)
highlight('StatusLine', Color8, Color7, nil)
highlight('WildMenu', Color7, Color9, nil)
highlight('Pmenu', Color7, Color9, nil)
highlight('PmenuSel', Color9, Color7, nil)
highlight('PmenuThumb', Color2, nil, nil)
highlight('DiffAdd', Color10, nil, nil)
highlight('DiffDelete', Color11, nil, nil)
highlight('Normal', Color7, Color9, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color7, nil, nil)
highlight('LineNr', nil, Color13, nil)
highlight('TabLine', Color7, Color14, nil)
highlight('TabLineSel', Color9, Color7, nil)
highlight('TabLineFill', Color7, Color14, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

highlight('Special', nil, Color2, nil)

-- finding some last little stragglers
highlight('Directory', nil, Color4, nil)
highlight('DiagnosticHint', nil, Color4, nil)
highlight('DiagnosticWarn', nil, Color4, nil)

link('TSString', 'String')
link('TSFunction', 'Function')
link('TSParameterReference', 'TSParameter')
link('TSOperator', 'Operator')
link('TSRepeat', 'Repeat')
link('Macro', 'Function')
link('TSTagDelimiter', 'Type')
link('TSNumber', 'Number')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSFloat', 'Number')
link('TSFuncMacro', 'Macro')
link('TSPunctBracket', 'MyTag')
link('Operator', 'Keyword')
link('TSKeyword', 'Keyword')
link('TSConditional', 'Conditional')
link('TSType', 'Type')
link('Conditional', 'Operator')
link('Whitespace', 'Comment')
link('TSParameter', 'Constant')
link('TSNamespace', 'TSType')
link('Folded', 'Comment')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('CursorLineNr', 'Identifier')
link('TSConstant', 'Constant')
link('TSField', 'Constant')
link('TSTag', 'MyTag')
link('TSProperty', 'TSField')
link('NonText', 'Comment')
link('Repeat', 'Conditional')
link('TSLabel', 'Type')
link('TSComment', 'Comment')
link('TelescopeNormal', 'Normal')

vim.fn.sign_define('DapStopped', { linehl = "PmenuThumb" })
