-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color6 = '#B0B0B0'
local Color0 = '#404040'
local Color1 = '#e476b2'
local Color7 = '#202020'
local Color8 = '#C0C0C0'
local Color10 = '#F0F0F0'
local Color2 = '#96b2e4'
local Color3 = '#76e4e4'
local Color5 = '#101010'
local Color9 = '#303030'
local Color4 = '#c296e4'

highlight('Comment', nil, Color0, nil)
highlight('Constant', nil, Color1, nil)
highlight('String', nil, Color1, nil)
highlight('Identifier', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color4, nil)
highlight('Type', nil, Color4, nil)
highlight('StatusLine', Color6, Color5, nil)
highlight('WildMenu', Color7, Color8, nil)
highlight('Pmenu', Color7, Color8, nil)
highlight('PmenuSel', Color8, Color7, nil)
highlight('PmenuThumb', Color7, Color8, nil)
highlight('Normal', Color7, Color8, nil)
highlight('Visual', Color9, nil, nil)
highlight('CursorLine', Color9, nil, nil)
highlight('ColorColumn', Color9, nil, nil)
highlight('SignColumn', Color7, nil, nil)
highlight('LineNr', nil, Color0, nil)
highlight('TabLine', Color7, Color6, nil)
highlight('TabLineSel', Color10, Color7, nil)
highlight('TabLineFill', Color7, Color6, nil)
highlight('TSPunctDelimiter', nil, Color8, nil)

link('TSFloat', 'Number')
link('TSConditional', 'Conditional')
link('TSTagDelimiter', 'Type')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSPunctBracket', 'MyTag')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSType', 'Type')
link('TSTag', 'MyTag')
link('TelescopeNormal', 'Normal')
link('Repeat', 'Conditional')
link('Macro', 'Function')
link('TSParameterReference', 'TSParameter')
link('TSRepeat', 'Repeat')
link('TSString', 'String')
link('Whitespace', 'Comment')
link('TSLabel', 'Type')
link('Folded', 'Comment')
link('NonText', 'Comment')
link('TSField', 'Constant')
link('TSFuncMacro', 'Macro')
link('TSProperty', 'TSField')
link('TSNumber', 'Number')
link('TSKeyword', 'Keyword')
link('CursorLineNr', 'Identifier')
link('TSComment', 'Comment')
link('Operator', 'Keyword')
link('TSConstant', 'Constant')
link('TSOperator', 'Operator')
link('TSNamespace', 'TSType')
link('TSParameter', 'Constant')
link('TSFunction', 'Function')
link('Conditional', 'Operator')
