-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color8 = '#ddddde'
local Color9 = '#242529'
local Color0 = '#7f8c98'
local Color1 = '#fe8170'
local Color13 = '#b7b7b7'
local Color11 = '#747478'
local Color3 = '#4db1cb'
local Color4 = '#d8c87c'
local Color7 = '#414045'
local Color10 = '#636f83'
local Color12 = '#303136'
local Color6 = '#a0a0a0'
local Color5 = '#dededf'
local Color14 = '#f7f7f7'
local Color2 = '#fe7ab2'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Keyword', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Number', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('StatusLine', Color6, Color7, nil)
highlight('WildMenu', Color9, Color8, nil)
highlight('Pmenu', Color9, Color8, nil)
highlight('PmenuSel', Color8, Color7, nil)
highlight('PmenuThumb', Color9, Color8, nil)
highlight('Normal', Color9, Color8, nil)
highlight('Visual', Color10, nil, nil)
highlight('CursorLine', Color10, nil, nil)
highlight('ColorColumn', Color10, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color11, nil)
highlight('TabLine', Color12, Color13, nil)
highlight('TabLineSel', Color14, Color7, nil)
highlight('TabLineFill', Color12, Color13, nil)
highlight('TSPunctDelimiter', nil, Color8, nil)

link('TSFunction', 'Function')
link('Operator', 'Keyword')
link('TSParameter', 'Constant')
link('TSKeyword', 'Keyword')
link('TSFuncMacro', 'Macro')
link('TSProperty', 'TSField')
link('TSType', 'Type')
link('TSParameterReference', 'TSParameter')
link('TelescopeNormal', 'Normal')
link('TSConditional', 'Conditional')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSTag', 'MyTag')
link('TSString', 'String')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSConstant', 'Constant')
link('TSField', 'Constant')
link('Conditional', 'Operator')
link('TSNamespace', 'TSType')
link('Repeat', 'Conditional')
link('TSNumber', 'Number')
link('TSTagDelimiter', 'Type')
link('Whitespace', 'Comment')
link('TSOperator', 'Operator')
link('NonText', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSLabel', 'Type')
link('TSRepeat', 'Repeat')
link('Macro', 'Function')
link('TSPunctBracket', 'MyTag')
link('TSFloat', 'Number')
link('Folded', 'Comment')
link('TSComment', 'Comment')
