-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color7 = '#414045'
local Color10 = '#444444'
local Color6 = '#a0a0a0'
local Color13 = '#f7f7f7'
local Color3 = '#53A5FB'
local Color8 = '#242529'
local Color9 = '#ffffff'
local Color5 = '#91D462'
local Color12 = '#b7b7b7'
local Color4 = '#FC5FA3'
local Color0 = '#6C7986'
local Color2 = '#9686F5'
local Color1 = '#FC6A5D'
local Color11 = '#303136'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Identifier', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color4, nil)
highlight('Function', nil, Color5, nil)
highlight('StatusLine', Color6, Color7, nil)
highlight('WildMenu', Color8, Color9, nil)
highlight('Pmenu', Color8, Color9, nil)
highlight('PmenuSel', Color9, Color7, nil)
highlight('PmenuThumb', Color8, Color9, nil)
highlight('Normal', Color8, Color9, nil)
highlight('Visual', Color10, nil, nil)
highlight('CursorLine', Color10, nil, nil)
highlight('ColorColumn', Color10, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('TabLine', Color11, Color12, nil)
highlight('TabLineSel', Color13, Color7, nil)
highlight('TabLineFill', Color11, Color12, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSComment', 'Comment')
link('TSTagDelimiter', 'Type')
link('TSRepeat', 'Repeat')
link('TSField', 'Constant')
link('Operator', 'Keyword')
link('TSKeyword', 'Keyword')
link('TSFloat', 'Number')
link('TSConstant', 'Constant')
link('Conditional', 'Operator')
link('CursorLineNr', 'Identifier')
link('TSTag', 'MyTag')
link('Folded', 'Comment')
link('TSFunction', 'Function')
link('TSString', 'String')
link('TSConditional', 'Conditional')
link('TSType', 'Type')
link('TSOperator', 'Operator')
link('TSFuncMacro', 'Macro')
link('NonText', 'Comment')
link('Whitespace', 'Comment')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSProperty', 'TSField')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSNamespace', 'TSType')
link('TSParameterReference', 'TSParameter')
link('TelescopeNormal', 'Normal')
link('TSParameter', 'Constant')
link('Repeat', 'Conditional')
link('TSLabel', 'Type')
link('Macro', 'Function')
link('TSPunctBracket', 'MyTag')
link('TSNumber', 'Number')
