-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color11 = '#e9e9e8'
local Color5 = '#ffffff'
local Color3 = '#666666'
local Color6 = '#656f81'
local Color7 = '#f7f7f6'
local Color4 = '#f6f6f5'
local Color1 = '#ee81b0'
local Color0 = '#89c0b4'
local Color12 = '#434343'
local Color8 = '#b5d5ff'
local Color9 = '#d4d4d4'
local Color10 = '#686969'
local Color2 = '#8adcfb'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color0, nil)
highlight('Keyword', nil, Color1, nil)
highlight('Type', nil, Color1, nil)
highlight('StatusLine', Color3, Color4, nil)
highlight('WildMenu', Color5, Color6, nil)
highlight('Pmenu', Color5, Color6, nil)
highlight('PmenuSel', Color6, Color7, nil)
highlight('PmenuThumb', Color5, Color6, nil)
highlight('Normal', Color5, Color6, nil)
highlight('Visual', Color8, nil, nil)
highlight('CursorLine', Color8, nil, nil)
highlight('ColorColumn', Color8, nil, nil)
highlight('SignColumn', Color5, nil, nil)
highlight('LineNr', nil, Color9, nil)
highlight('TabLine', Color11, Color10, nil)
highlight('TabLineSel', Color12, Color7, nil)
highlight('TabLineFill', Color11, Color10, nil)
highlight('TSPunctDelimiter', nil, Color6, nil)

link('TSParameter', 'Constant')
link('Repeat', 'Conditional')
link('Folded', 'Comment')
link('TSComment', 'Comment')
link('TSLabel', 'Type')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Operator', 'Keyword')
link('TSNumber', 'Number')
link('TSNamespace', 'TSType')
link('TSOperator', 'Operator')
link('TSFunction', 'Function')
link('TelescopeNormal', 'Normal')
link('TSProperty', 'TSField')
link('TSConditional', 'Conditional')
link('Whitespace', 'Comment')
link('TSType', 'Type')
link('TSString', 'String')
link('TSConstant', 'Constant')
link('Conditional', 'Operator')
link('TSKeyword', 'Keyword')
link('TSPunctBracket', 'MyTag')
link('TSFuncMacro', 'Macro')
link('TSParameterReference', 'TSParameter')
link('TSTagDelimiter', 'Type')
link('TSTag', 'MyTag')
link('TSField', 'Constant')
link('TSRepeat', 'Repeat')
link('CursorLineNr', 'Identifier')
link('Macro', 'Function')
link('NonText', 'Comment')
link('TSFloat', 'Number')
