-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color13 = '#2c2c2b'
local Color8 = '#403e3e'
local Color6 = '#E12DA0'
local Color4 = '#53b3b1'
local Color0 = '#51C34F'
local Color11 = '#6e6e6e'
local Color3 = '#e7e8eB'
local Color2 = '#FF5370'
local Color15 = '#ebebeb'
local Color10 = '#232222'
local Color5 = '#ec3d37'
local Color7 = '#b4b3b3'
local Color1 = '#34c9c6'
local Color14 = '#9f9f9e'
local Color12 = '#747478'
local Color9 = '#dddddd'

highlight('Comment', nil, Color0, nil)
highlight('Number', nil, Color1, nil)
highlight('Error', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('TSCharacter', nil, Color4, nil)
highlight('String', nil, Color5, nil)
highlight('Number', nil, Color3, nil)
highlight('Keyword', nil, Color6, nil)
highlight('StatusLine', Color7, Color8, nil)
highlight('WildMenu', Color10, Color9, nil)
highlight('Pmenu', Color10, Color9, nil)
highlight('PmenuSel', Color9, Color8, nil)
highlight('PmenuThumb', Color10, Color9, nil)
highlight('Normal', Color10, Color9, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color10, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color13, Color14, nil)
highlight('TabLineSel', Color15, Color8, nil)
highlight('TabLineFill', Color13, Color14, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSComment', 'Comment')
link('TSProperty', 'TSField')
link('TSFloat', 'Number')
link('TSNamespace', 'TSType')
link('Repeat', 'Conditional')
link('TSPunctBracket', 'MyTag')
link('TSType', 'Type')
link('TSParameter', 'Constant')
link('TelescopeNormal', 'Normal')
link('Operator', 'Keyword')
link('TSConstant', 'Constant')
link('TSLabel', 'Type')
link('TSTagDelimiter', 'Type')
link('TSKeyword', 'Keyword')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Conditional', 'Operator')
link('Macro', 'Function')
link('TSOperator', 'Operator')
link('TSConditional', 'Conditional')
link('TSString', 'String')
link('TSTag', 'MyTag')
link('Whitespace', 'Comment')
link('TSParameterReference', 'TSParameter')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSField', 'Constant')
link('CursorLineNr', 'Identifier')
link('Folded', 'Comment')
link('TSRepeat', 'Repeat')
link('TSFuncMacro', 'Macro')
link('TSNumber', 'Number')
link('NonText', 'Comment')
link('TSFunction', 'Function')
