-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color1 = '#DF0002'
local Color4 = '#C800A4'
local Color13 = '#c6c6c6'
local Color14 = '#444444'
local Color11 = '#b5d5ff'
local Color8 = '#000000'
local Color6 = '#ededed'
local Color5 = '#C900A4'
local Color3 = '#275A5E'
local Color2 = '#3A00DC'
local Color10 = '#dbdbdb'
local Color0 = '#008E00'
local Color7 = '#666666'
local Color12 = '#bbbbbb'
local Color9 = '#ffffff'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color5, nil)
highlight('StatusLine', Color7, Color6, nil)
highlight('WildMenu', Color9, Color8, nil)
highlight('Pmenu', Color9, Color8, nil)
highlight('PmenuSel', Color8, Color10, nil)
highlight('PmenuThumb', Color9, Color8, nil)
highlight('Normal', Color9, Color8, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color13, Color7, nil)
highlight('TabLineSel', Color14, Color10, nil)
highlight('TabLineFill', Color13, Color7, nil)
highlight('TSPunctDelimiter', nil, Color8, nil)

link('TSRepeat', 'Repeat')
link('Folded', 'Comment')
link('Whitespace', 'Comment')
link('TSString', 'String')
link('TSPunctBracket', 'MyTag')
link('Conditional', 'Operator')
link('TSTagDelimiter', 'Type')
link('TSConstant', 'Constant')
link('TSParameterReference', 'TSParameter')
link('Repeat', 'Conditional')
link('Operator', 'Keyword')
link('TSField', 'Constant')
link('TSType', 'Type')
link('TSProperty', 'TSField')
link('TSFuncMacro', 'Macro')
link('TSLabel', 'Type')
link('TSKeyword', 'Keyword')
link('TSParameter', 'Constant')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('NonText', 'Comment')
link('TSConditional', 'Conditional')
link('TSNumber', 'Number')
link('TSFloat', 'Number')
link('TSTag', 'MyTag')
link('TSNamespace', 'TSType')
link('TSFunction', 'Function')
link('TSComment', 'Comment')
link('Macro', 'Function')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TelescopeNormal', 'Normal')
link('CursorLineNr', 'Identifier')
link('TSOperator', 'Operator')
