-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color8 = '#414045'
local Color5 = '#ec3d37'
local Color0 = '#51C34F'
local Color4 = '#53b3b1'
local Color11 = '#636f83'
local Color13 = '#b7b7b7'
local Color7 = '#a0a0a0'
local Color6 = '#E12DA0'
local Color1 = '#34c9c6'
local Color15 = '#f7f7f7'
local Color3 = '#e7e8eB'
local Color14 = '#303136'
local Color9 = '#242529'
local Color10 = '#ddddde'
local Color12 = '#747478'
local Color2 = '#FF5370'

highlight('Comment', nil, Color0, nil)
highlight('Number', nil, Color1, nil)
highlight('Error', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('TSCharacter', nil, Color4, nil)
highlight('String', nil, Color5, nil)
highlight('Keyword', nil, Color6, nil)
highlight('StatusLine', Color7, Color8, nil)
highlight('WildMenu', Color9, Color10, nil)
highlight('Pmenu', Color9, Color10, nil)
highlight('PmenuSel', Color10, Color8, nil)
highlight('PmenuThumb', Color9, Color10, nil)
highlight('Normal', Color9, Color10, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color14, Color13, nil)
highlight('TabLineSel', Color15, Color8, nil)
highlight('TabLineFill', Color14, Color13, nil)
highlight('TSPunctDelimiter', nil, Color10, nil)

link('NonText', 'Comment')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSNamespace', 'TSType')
link('TSType', 'Type')
link('TSComment', 'Comment')
link('TSFloat', 'Number')
link('Macro', 'Function')
link('Repeat', 'Conditional')
link('Folded', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSNumber', 'Number')
link('TSPunctBracket', 'MyTag')
link('TSParameterReference', 'TSParameter')
link('TelescopeNormal', 'Normal')
link('TSString', 'String')
link('TSFuncMacro', 'Macro')
link('Operator', 'Keyword')
link('TSFunction', 'Function')
link('TSProperty', 'TSField')
link('TSConstant', 'Constant')
link('TSTag', 'MyTag')
link('TSKeyword', 'Keyword')
link('TSRepeat', 'Repeat')
link('Conditional', 'Operator')
link('TSTagDelimiter', 'Type')
link('TSParameter', 'Constant')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Whitespace', 'Comment')
link('TSField', 'Constant')
link('TSLabel', 'Type')
link('TSOperator', 'Operator')
